export const mockHistoricalTrends = {
  "West Africa": [
    { week: -8, value: 3 },
    { week: -7, value: 2 },
    { week: -6, value: 4 },
    { week: -5, value: 1 },
    { week: -4, value: 3 },
    { week: -3, value: 2 },
    { week: -2, value: 4 },
    { week: -1, value: 2 },
  ],
  "Southeast Asia": [
    { week: -8, value: 4 },
    { week: -7, value: 5 },
    { week: -6, value: 3 },
    { week: -5, value: 4 },
    { week: -4, value: 6 },
    { week: -3, value: 3 },
    { week: -2, value: 4 },
    { week: -1, value: 5 },
  ],
  "Indian Ocean": [
    { week: -8, value: 2 },
    { week: -7, value: 3 },
    { week: -6, value: 1 },
    { week: -5, value: 2 },
    { week: -4, value: 0 },
    { week: -3, value: 1 },
    { week: -2, value: 3 },
    { week: -1, value: 2 },
  ],
  Americas: [
    { week: -8, value: 1 },
    { week: -7, value: 0 },
    { week: -6, value: 2 },
    { week: -5, value: 1 },
    { week: -4, value: 1 },
    { week: -3, value: 0 },
    { week: -2, value: 1 },
    { week: -1, value: 1 },
  ],
  Europe: [
    { week: -8, value: 2 },
    { week: -7, value: 1 },
    { week: -6, value: 2 },
    { week: -5, value: 3 },
    { week: -4, value: 2 },
    { week: -3, value: 4 },
    { week: -2, value: 2 },
    { week: -1, value: 1 },
  ],
};
