export const mockHistoricalTrends = {
  "West Africa": [
    { month: "May", value: 8 },
    { month: "Jun", value: 6 },
    { month: "Jul", value: 9 },
    { month: "Aug", value: 5 },
    { month: "Sep", value: 7 },
    { month: "Oct", value: 10 },
  ],
  "Southeast Asia": [
    { month: "May", value: 12 },
    { month: "Jun", value: 15 },
    { month: "Jul", value: 10 },
    { month: "Aug", value: 14 },
    { month: "Sep", value: 16 },
    { month: "Oct", value: 13 },
  ],
  "Indian Ocean": [
    { month: "May", value: 6 },
    { month: "Jun", value: 4 },
    { month: "Jul", value: 3 },
    { month: "Aug", value: 5 },
    { month: "Sep", value: 2 },
    { month: "Oct", value: 4 },
  ],
  Americas: [
    { month: "May", value: 4 },
    { month: "Jun", value: 3 },
    { month: "Jul", value: 5 },
    { month: "Aug", value: 3 },
    { month: "Sep", value: 2 },
    { month: "Oct", value: 3 },
  ],
  Europe: [
    { month: "May", value: 5 },
    { month: "Jun", value: 3 },
    { month: "Jul", value: 6 },
    { month: "Aug", value: 8 },
    { month: "Sep", value: 7 },
    { month: "Oct", value: 4 },
  ],
};
