[build]
command = "cd src/apps/mara && npm run build"
publish = "src/apps/mara/dist"
functions = "functions"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Functions configuration
[functions]
directory = "functions"
node_bundler = "esbuild"

# Collectors and processor run at different times to spread the load
[functions."collect-recaap"]
schedule = "0,30 * * * *"

[functions."collect-ukmto"]
schedule = "5,35 * * * *"

[functions."collect-mdat"]
schedule = "15,45 * * * *"

[functions."collect-icc"]
schedule = "20,50 * * * *"

[functions."process-incidents"]
schedule = "25,55 * * * *"
