[build]
publish = "dist"
command = "npm install && npm run build"
functions = "functions"

[build.environment]
NODE_VERSION = "18"

[dev]
command = "turbo run dev --filter @mara/client"
framework = "#custom"
targetPort = 3000

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Functions configuration
[functions]
directory = "functions"
node_bundler = "esbuild"
external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[functions.generate-pdf]
included_files = []
external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
