-- Email service tables for new Resend implementation
-- These tables run alongside existing email functionality

-- Set search path to public schema
SET search_path TO public;

-- Email templates table
CREATE TABLE IF NOT EXISTS public.email_templates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    html_template TEXT NOT NULL,
    text_template TEXT NOT NULL,
    variables TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Email tracking table
CREATE TABLE IF NOT EXISTS public.email_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id TEXT NOT NULL UNIQUE,
    template_id TEXT REFERENCES email_templates(id),
    recipient_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE,
    opened_at TIMESTAMP WITH TIME ZONE,
    clicked_at TIMESTAMP WITH TIME ZONE,
    status TEXT NOT NULL CHECK (status IN ('queued', 'sent', 'delivered', 'failed')),
    error TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_tracking_status ON email_tracking(status);
CREATE INDEX IF NOT EXISTS idx_email_tracking_sent_at ON email_tracking(sent_at);
CREATE INDEX IF NOT EXISTS idx_email_tracking_recipient ON email_tracking(recipient_email);

-- Function for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for timestamp updates
CREATE TRIGGER update_email_templates_updated_at
    BEFORE UPDATE ON email_templates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable row level security
ALTER TABLE email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_tracking ENABLE ROW LEVEL SECURITY;

-- Policies for authenticated users
CREATE POLICY "Allow authenticated read access to email templates"
    ON email_templates FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow authenticated read access to email tracking"
    ON email_tracking FOR SELECT
    TO authenticated
    USING (true);

-- Policies for service role
CREATE POLICY "Allow service role full access to email templates"
    ON email_templates FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow service role full access to email tracking"
    ON email_tracking FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Insert default flash report template
INSERT INTO email_templates (
    id,
    name,
    subject,
    html_template,
    text_template,
    variables
) VALUES (
    'flash-report',
    'Flash Report Template',
    'Maritime Flash Report - {{location}}',
    '<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flash Maritime Alert</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background-color: #f3f4f6;">
  <div style="text-align: center; margin-bottom: 20px;">
    <img src="{{logo}}" alt="{{companyName}}" style="max-width: 180px; height: auto;">
  </div>
  
  <div style="max-width: 800px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.06);">
    <div style="background-color: #FFF7ED; padding: 24px; border-bottom: 1px solid #FFEDD5;">
      <div style="display: flex; justify-content: space-between; align-items: flex-start;">
        <div>
          <div style="display: flex; gap: 8px; margin-bottom: 8px;">
            <span style="display: inline-block; padding: 4px 10px; background-color: #FEE2E2; border-radius: 9999px; color: #991B1B; font-size: 14px; font-weight: bold;">Alert ID: {{id}}</span>
            <span style="display: inline-block; padding: 4px 10px; background-color: #FEF3C7; border-radius: 9999px; color: #92400E; font-size: 14px; font-weight: bold;">{{type}}</span>
          </div>
          <h1 style="font-size: 24px; font-weight: bold; margin-top: 8px; margin-bottom: 4px; color: {{primaryColor}};">{{vesselName}}</h1>
          <p style="font-size: 14px; color: #4B5563; margin: 0;">
            <span style="display: inline-block; margin-right: 10px; color: #111827;">Type: {{vesselType}}</span> | 
            <span style="display: inline-block; margin: 0 10px; color: #111827;">IMO: {{vesselIMO}}</span> | 
            <span style="display: inline-block; margin-left: 10px; color: #111827;">Flag: {{vesselFlag}}</span>
          </p>
        </div>
        <div style="text-align: right;">
          <p style="font-size: 14px; color: #6B7280; margin: 0 0 4px 0;">Reported</p>
          <p style="font-size: 16px; font-weight: 600; color: #111827; margin: 0;">{{date}}</p>
        </div>
      </div>
    </div>

    {{#if publicUrl}}
    <div style="background-color: #EFF6FF; padding: 16px; text-align: center; border-bottom: 1px solid #DBEAFE;">
      <p style="margin: 0; font-size: 14px; color: #1E3A8A;">
        This is an email snapshot. 
        <a href="{{publicUrl}}" style="color: #2563EB; font-weight: 600; text-decoration: underline;">View this Flash Report online</a> 
        for the latest information.
      </p>
    </div>
    {{/if}}

    <div style="padding: 24px; border-bottom: 1px solid #E5E7EB;">
      <h2 style="font-size: 18px; font-weight: 600; color: {{primaryColor}}; margin-top: 0; margin-bottom: 16px;">Location</h2>
      <p style="font-size: 16px; font-weight: 600; color: #111827; margin: 0 0 4px 0;">{{location}}</p>
      <p style="font-size: 14px; color: #6B7280; margin: 0;">{{coordinates}}</p>
    </div>

    <div style="padding: 24px; border-bottom: 1px solid #E5E7EB;">
      <h2 style="font-size: 18px; font-weight: 600; color: {{primaryColor}}; margin-top: 0; margin-bottom: 16px;">Incident Details</h2>
      <div style="background-color: #F9FAFB; padding: 16px; border-radius: 6px;">
        <h3 style="font-size: 16px; font-weight: 600; margin-top: 0; margin-bottom: 8px; color: #111827;">Description</h3>
        <p style="font-size: 14px; line-height: 1.5; color: #374151; margin: 0;">{{description}}</p>
      </div>
    </div>

    <div style="padding: 24px;">
      <h2 style="font-size: 18px; font-weight: 600; color: {{primaryColor}}; margin-top: 0; margin-bottom: 16px;">Analysis</h2>
      <div style="background-color: #FFF7ED; padding: 16px; border-radius: 6px; border-left: 4px solid {{secondaryColor}};">
        <h3 style="font-size: 16px; font-weight: 600; margin-top: 0; margin-bottom: 8px; color: #111827;">Key Findings</h3>
        <p style="font-size: 14px; line-height: 1.5; color: #374151; margin: 0;">{{analysis}}</p>
      </div>
      
      {{#if recommendations}}
      <div style="background-color: #F0F9FF; padding: 16px; border-radius: 6px; border-left: 4px solid {{primaryColor}}; margin-top: 24px;">
        <h3 style="font-size: 16px; font-weight: 600; margin-top: 0; margin-bottom: 8px; color: #111827;">Recommendations</h3>
        <p style="font-size: 14px; line-height: 1.5; color: #374151; margin: 0;">{{recommendations}}</p>
      </div>
      {{/if}}
    </div>

    <div style="margin-top: 30px; padding: 20px 24px 24px; text-align: center; color: #6B7280; font-size: 12px; border-top: 1px solid #E5E7EB;">
      <p style="margin: 4px 0;">© {{year}} {{companyName}}. All rights reserved.</p>
      <p style="margin: 4px 0;">This alert is confidential and for the intended recipient only.</p>
    </div>
  </div>
</body>
</html>',
    'Maritime Flash Report

Alert ID: {{id}}
Type: {{type}}
Location: {{location}}

Vessel: {{vesselName}}
Type: {{vesselType}}
IMO: {{vesselIMO}}
Flag: {{vesselFlag}}

Description:
{{description}}

Analysis:
{{analysis}}

{{#if recommendations}}
Recommendations:
{{recommendations}}
{{/if}}

View online: {{publicUrl}}

© {{year}} {{companyName}}
This alert is confidential.',
    ARRAY[
        'id', 'type', 'location', 'coordinates',
        'vesselName', 'vesselType', 'vesselFlag', 'vesselIMO',
        'date', 'status', 'crewStatus',
        'description', 'analysis', 'recommendations',
        'logo', 'companyName', 'primaryColor', 'secondaryColor',
        'publicUrl', 'year'
    ]
) ON CONFLICT (id) DO NOTHING;

-- Down migration
CREATE OR REPLACE FUNCTION drop_email_service_tables() RETURNS void AS $$
BEGIN
    DROP TABLE IF EXISTS email_tracking;
    DROP TABLE IF EXISTS email_templates;
    DROP FUNCTION IF EXISTS update_updated_at_column();
END;
$$ LANGUAGE plpgsql;
